### ISSUE TITLE
Some questions about the codes

### ISSUE THREAD

**Issue by Baiyu6666** [ajlangley/cpo-pytorch#2]
Thanks for your sharing. I just have some questions when I'm reading your codes.

Q1  In line_search.py  Line 39
`if constraints_satisfied(step_len * search_dir, step_len):`

I think it should be constraints_satisfied(search_dir, step_len), because in cpo.py Line 190 ,test_policy = current_policy + step_len * search_dir. It seems that you multiply step_len by twice.

Q2  in cpo.py Line 205
`cost_cond = step_len * torch.matmul(constraint_grad, search_dir) <= max(-c, 0.0)`

It seems that you want test the constraint of the linearized problem (Equation 11 in the CPO paper). But according to the original paper (the last line in Algorithm 1 ), it should be  testd the non-linearized problem (Equation 10 in the CPO paper).
So the right code may be
`cost_cond = test_cost<= max(-c, 0.0)`
(Besides, I notice the test_cost is calculated but not used in the codes)

**Comment by ajlangley** [comment]
On the first point regarding line 39 in line_search.py, you are correct. In regard to the last thing about test_cost not being used, I think that must be leftover from something I'd previously tried that didn't work.

Now, about that line in Algorithm 1, the way I interpret this is that they enforce the satisfaction of the constraints in (10) by approximating it with (11). I believe I tried it the other way and that the short answer is, it just didn't work. There's a code base written by Achaim himself that you can refer to, and if I remember correctly that's how he does it.
