### ISSUE TITLE
[question] How to turn my custom environment into an environment suitable for CPO?

### ISSUE THREAD

**Issue by kosmylo** [ajlangley/cpo-pytorch#3]
I have a custom environment that I use to train PPO and SAC agents on it. I have some constraints that I penalize through the reward function when they are violated and I would like to test the performance of CPO in this context. My question is what steps should I follow to be able to use your CPO implementation. For example, how can I integrate a cost function?

**Comment by ajlangley** [comment]
I'd suggest you take a look at envs/point_gather.py for an example. Specifically, look at the step() function. Broadly speaking, at every iteration the environment needs to return an observation, a reward signal (just the reward, without any constraint information added to it), whether the simulation is done, and a dictionary with 'reward' and 'constraint_cost' fields. Note that the implication here is that the reward and constraint signals need to be separate, so I don't know if that conflicts with what that you said about "penalizing constraints through the reward function."

Your environment should have, at the minimum, a reset function, and a step function that takes an action as its argument and returns the values described above.

Then, you'll need to modify the make_env function in simulators.py to initialize and return an instance of your environment. 

I hope this will help you get started.
